function [f, df, d2f] = rbf_hypervel(param)
%RBF_HYPERVEL Summary of this function goes here
%   Detailed explanation goes here
if ~isfield(param,'sigma')
    error('Define sigma');
end
f = @(x,y,v)...
    exp(-vecnorm(repmat(x,size(y,1),1)-repelem(y,size(x,1),1),2,2).^2/...
    2/vecnorm(repmat(v,size(y,1),1))^2);

% Gradient
if nargout > 1
    df = @(x,y,v)...
         (repmat(x,size(y,1),1)-repelem(y,size(x,1),1))/...
         vecnorm(repmat(v,size(y,1),1))^2.*f(x,y,v);   
end

% Hessian
if nargout > 2
    d2f = @(x,y,v)...
          (-repmat(reshape(eye(size(x,2)),1,[]),size(x,1)*size(y,1),1)+...
          (repelem(repmat(x,size(y,1),1)-repelem(y,size(x,1),1),1,size(x,2)).*...
          repmat(repmat(x,size(y,1),1)-repelem(y,size(x,1),1),1,size(x,2)))/vecnorm(repmat(v,size(y,1),1))^2)/...
          vecnorm(repmat(v,size(y,1),1))^2.*f(x,y,v);
end
end
