function init(obj)
%INIT Summary of this function goes here
%   Detailed explanation goes here
obj.options_ = struct('limits', [0 100 0 100],...
                     'calc_vel', true,...
                     'get_time', true,...
                     'get_labels', true ...
                     );
                 
obj.demo_struct_ = struct;
end

