clear; close all; clc;

%% Drawing options
gen_options = struct('limits', [0 100 0 100],...
                     'calc_vel', true,...
                     'get_time', true,...
                     'get_labels', true ...
                     );
[demo, demo_struct] = GenerateDemos(gen_options);
close;

save('demos/ds_demo.mat', 'demo', 'demo_struct');